- name: Генерация SSH-ключа на контроллере
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Проверить, существует ли ключ
      stat:
        path: /etc/ansible/start_project/files/ansible_id_rsa
      register: keypair

    - name: Сгенерировать ключ, если его нет
      command: ssh-keygen -t rsa -b 4096 -f /etc/ansible/start_project/files/ansible_id_rsa -N ""
      when: not keypair.stat.exists


- name: Подготовка удаленного сервера
  hosts: all
  become: yes
  gather_facts: no

  pre_tasks:
    - name: Установить Python (если не установлен)
      raw: test -e /usr/bin/python3 || (apt update && apt install -y python3)
      changed_when: false

  tasks:
    - name: Создать пользователя ansible
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        create_home: yes
        password: "{{ '12345' | password_hash('sha512') }}"  # Устанавливаем пароль для пользователя ansible

    - name: Скопировать публичный ключ
      ansible.builtin.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/etc/ansible/start_project/files/ansible_id_rsa.pub') }}"

    - name: Создать директорию /etc/sudoers.d (если отсутствует)
      ansible.builtin.file:
        path: /etc/sudoers.d
        state: directory
        mode: '0750'

    - name: Добавить sudo без пароля
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ansible
        content: "ansible ALL=(ALL) NOPASSWD:ALL\n"
        mode: '0440'

    - name: Убедиться, что sudo установлен
      ansible.builtin.package:
        name: sudo
        state: present


